// FinanceOS — Mock Data Layer

export const user = {
  name: "Marcus Johnson",
  email: "marcus@financeOS.com",
  avatar: "MJ",
  role: "Owner",
  financialScore: 782,
  scoreChange: +12,
  netWorth: 2_847_500,
  netWorthChange: 3.4,
  liquidCash: 184_320,
  monthlyBurnRate: 28_450,
  debtToIncome: 0.31,
  familyMembers: [
    { name: "Alicia Johnson", relation: "Spouse", avatar: "AJ" },
    { name: "Tyler Johnson", relation: "Son", avatar: "TJ" },
  ],
};

export const businesses = [
  {
    id: "biz-1",
    name: "Johnson Real Estate LLC",
    type: "Real Estate",
    ein: "84-1234567",
    revenue: 485_000,
    expenses: 312_000,
    profit: 173_000,
    profitMargin: 35.7,
    employees: 8,
    status: "active",
    color: "indigo",
    accounts: [
      { name: "Chase Business Checking", balance: 64_200, type: "checking" },
      { name: "Chase Business Savings", balance: 120_000, type: "savings" },
    ],
    monthlyRevenue: [38000, 42000, 39000, 47000, 51000, 43000, 48000, 52000, 46000, 44000, 39000, 41000],
    vendors: [
      { name: "HomePro Maintenance", category: "Maintenance", monthly: 4200 },
      { name: "Premier Property Mgmt", category: "Management", monthly: 8500 },
      { name: "LegalShield LLC", category: "Legal", monthly: 1200 },
    ],
    payables: [
      { vendor: "HomePro Maintenance", amount: 4200, due: "2026-02-01", status: "pending" },
      { vendor: "Chase Mortgage — 320 Oak", amount: 6800, due: "2026-02-05", status: "pending" },
    ],
    team: [
      { name: "Sandra Lee", role: "Property Manager", email: "sandra@jrellc.com" },
      { name: "Kevin Park", role: "Leasing Agent", email: "kevin@jrellc.com" },
      { name: "Maria Torres", role: "Accountant", email: "maria@jrellc.com" },
    ],
    bills: [
      { name: "Office Rent", amount: 3200, frequency: "monthly" },
      { name: "Business Insurance", amount: 1800, frequency: "monthly" },
      { name: "QuickBooks", amount: 85, frequency: "monthly" },
    ],
  },
  {
    id: "biz-2",
    name: "MJ Tech Consulting",
    type: "Technology",
    ein: "85-7654321",
    revenue: 290_000,
    expenses: 148_000,
    profit: 142_000,
    profitMargin: 48.9,
    employees: 4,
    status: "active",
    color: "violet",
    accounts: [
      { name: "Bank of America Checking", balance: 38_400, type: "checking" },
    ],
    monthlyRevenue: [22000, 24000, 26000, 28000, 25000, 30000, 27000, 32000, 29000, 31000, 26000, 28000],
    vendors: [
      { name: "AWS", category: "Cloud Infra", monthly: 3200 },
      { name: "HubSpot", category: "CRM", monthly: 800 },
      { name: "Adobe CC", category: "Software", monthly: 120 },
    ],
    payables: [
      { vendor: "AWS", amount: 3200, due: "2026-02-03", status: "pending" },
      { vendor: "HubSpot", amount: 800, due: "2026-02-08", status: "pending" },
    ],
    team: [
      { name: "David Chen", role: "Lead Developer", email: "david@mjtechco.com" },
      { name: "Priya Nair", role: "UX Designer", email: "priya@mjtechco.com" },
    ],
    bills: [
      { name: "Slack", amount: 120, frequency: "monthly" },
      { name: "GitHub Teams", amount: 84, frequency: "monthly" },
    ],
  },
  {
    id: "biz-3",
    name: "Urban Eats Group",
    type: "Restaurant",
    ein: "86-9876543",
    revenue: 820_000,
    expenses: 694_000,
    profit: 126_000,
    profitMargin: 15.4,
    employees: 22,
    status: "active",
    color: "emerald",
    accounts: [
      { name: "Wells Fargo Business", balance: 41_800, type: "checking" },
      { name: "Savings Reserve", balance: 18_000, type: "savings" },
    ],
    monthlyRevenue: [65000, 70000, 68000, 72000, 75000, 80000, 78000, 82000, 70000, 68000, 60000, 62000],
    vendors: [
      { name: "Sysco Foods", category: "Food Supply", monthly: 32000 },
      { name: "Republic Services", category: "Waste Mgmt", monthly: 1800 },
      { name: "Toast POS", category: "Technology", monthly: 450 },
    ],
    payables: [
      { vendor: "Sysco Foods", amount: 32000, due: "2026-01-31", status: "overdue" },
      { vendor: "Republic Services", amount: 1800, due: "2026-02-10", status: "pending" },
    ],
    team: [
      { name: "Chef Antoine", role: "Head Chef", email: "chef@urbaneats.com" },
      { name: "Jess Williams", role: "GM", email: "jess@urbaneats.com" },
    ],
    bills: [
      { name: "Restaurant Lease", amount: 14000, frequency: "monthly" },
      { name: "Liquor License", amount: 500, frequency: "monthly" },
    ],
  },
];

export const personalFinances = {
  mortgages: [
    {
      id: "m-1",
      property: "4821 Riverside Drive (Primary)",
      lender: "Chase Mortgage",
      balance: 428_000,
      originalAmount: 520_000,
      rate: 6.875,
      payment: 3_420,
      dueDate: 1,
      equity: 312_000,
      estimatedValue: 740_000,
      type: "30yr Fixed",
      refinanceOpportunity: true,
      refinanceSavings: 340,
    },
    {
      id: "m-2",
      property: "320 Oak Ave (Rental)",
      lender: "Wells Fargo",
      balance: 284_000,
      originalAmount: 320_000,
      rate: 5.25,
      payment: 2_180,
      dueDate: 5,
      equity: 196_000,
      estimatedValue: 480_000,
      type: "30yr Fixed",
      refinanceOpportunity: false,
      refinanceSavings: 0,
    },
  ],
  vehicles: [
    {
      id: "v-1",
      vehicle: "2024 Mercedes GLE 450",
      lender: "Mercedes-Benz Financial",
      balance: 68_400,
      payment: 1_285,
      rate: 5.9,
      dueDate: 15,
      remainingMonths: 54,
    },
    {
      id: "v-2",
      vehicle: "2023 Tesla Model Y",
      lender: "Tesla Financial",
      balance: 32_800,
      payment: 786,
      rate: 3.99,
      dueDate: 20,
      remainingMonths: 42,
    },
  ],
  creditCards: [
    { name: "Chase Sapphire Reserve", balance: 4_200, limit: 30_000, rate: 22.99, payment: 420, due: 8 },
    { name: "Amex Platinum", balance: 1_850, limit: 25_000, rate: 21.49, payment: 185, due: 12 },
    { name: "Capital One Venture", balance: 680, limit: 15_000, rate: 19.99, payment: 68, due: 18 },
  ],
  bankAccounts: [
    { name: "Chase Premier Checking", institution: "Chase", balance: 84_200, type: "checking" },
    { name: "High-Yield Savings", institution: "Marcus by Goldman", balance: 62_400, type: "savings", apy: 4.75 },
    { name: "Brokerage Account", institution: "Fidelity", balance: 387_500, type: "investment" },
    { name: "Roth IRA", institution: "Fidelity", balance: 142_800, type: "retirement" },
    { name: "401(k)", institution: "Vanguard", balance: 284_000, type: "retirement" },
  ],
  insurancePolicies: [
    { name: "Homeowners Insurance", provider: "State Farm", premium: 280, frequency: "monthly", coverage: 850000, type: "home" },
    { name: "Auto Insurance", provider: "Progressive", premium: 312, frequency: "monthly", coverage: 300000, type: "auto" },
    { name: "Term Life — $2M", provider: "Northwestern Mutual", premium: 185, frequency: "monthly", coverage: 2000000, type: "life" },
    { name: "Umbrella Policy", provider: "State Farm", premium: 96, frequency: "monthly", coverage: 2000000, type: "umbrella" },
    { name: "Business Owners Policy", provider: "Hiscox", premium: 420, frequency: "monthly", coverage: 1500000, type: "business" },
  ],
};

export const assets = {
  realEstate: 1_220_000,
  vehicles: 148_000,
  investments: 814_300,
  businessEquity: 942_000,
  cash: 184_320,
  other: 28_500,
  total: 3_337_120,
};

export const liabilities = {
  mortgages: 712_000,
  vehicleLoans: 101_200,
  creditCards: 6_730,
  businessDebt: 0,
  studentLoans: 0,
  otherDebt: 0,
  total: 819_930,
};

export const cashFlow = {
  thisMonth: {
    income: 62_400,
    expenses: 34_200,
    net: 28_200,
    trend: "up",
  },
  last6Months: [
    { month: "Aug", income: 54200, expenses: 30100 },
    { month: "Sep", income: 58400, expenses: 32800 },
    { month: "Oct", income: 61200, expenses: 34500 },
    { month: "Nov", income: 55800, expenses: 31200 },
    { month: "Dec", income: 70200, expenses: 42100 },
    { month: "Jan", income: 62400, expenses: 34200 },
  ],
};

export const upcomingPayments = [
  { name: "Chase Mortgage — Primary", amount: 3420, due: "2026-02-01", category: "mortgage", status: "due" },
  { name: "Sysco Foods (Urban Eats)", amount: 32000, due: "2026-01-31", category: "business", status: "overdue" },
  { name: "AWS (MJ Tech)", amount: 3200, due: "2026-02-03", category: "business", status: "upcoming" },
  { name: "Mercedes-Benz Financial", amount: 1285, due: "2026-02-05", category: "vehicle", status: "upcoming" },
  { name: "Wells Fargo Mortgage", amount: 2180, due: "2026-02-05", category: "mortgage", status: "upcoming" },
  { name: "State Farm — Homeowners", amount: 280, due: "2026-02-08", category: "insurance", status: "upcoming" },
  { name: "Chase Sapphire Reserve", amount: 420, due: "2026-02-08", category: "credit", status: "upcoming" },
  { name: "Amex Platinum", amount: 185, due: "2026-02-12", category: "credit", status: "upcoming" },
];

export const loans = [
  {
    id: "loan-1",
    entity: "Johnson Real Estate LLC",
    lender: "Chase Bank",
    type: "Commercial Real Estate",
    originalAmount: 320_000,
    balance: 284_000,
    rate: 5.25,
    term: 360,
    monthsElapsed: 48,
    payment: 2_180,
    nextPayment: "2026-02-05",
    status: "current",
  },
  {
    id: "loan-2",
    entity: "Personal",
    lender: "Chase Mortgage",
    type: "Primary Mortgage",
    originalAmount: 520_000,
    balance: 428_000,
    rate: 6.875,
    term: 360,
    monthsElapsed: 24,
    payment: 3_420,
    nextPayment: "2026-02-01",
    status: "current",
  },
  {
    id: "loan-3",
    entity: "Personal",
    lender: "Mercedes-Benz Financial",
    type: "Auto Loan",
    originalAmount: 88_000,
    balance: 68_400,
    rate: 5.9,
    term: 72,
    monthsElapsed: 18,
    payment: 1_285,
    nextPayment: "2026-02-15",
    status: "current",
  },
];

export const aiInsights = [
  {
    id: "ai-1",
    type: "refinance",
    priority: "high",
    title: "Refinance Opportunity: Primary Residence",
    summary: "Rates have dropped. Refinancing your primary mortgage from 6.875% to ~6.1% could save you $340/month.",
    impact: 4080,
    impactLabel: "Annual Savings",
    action: "Review Refinance Options",
  },
  {
    id: "ai-2",
    type: "debt",
    priority: "medium",
    title: "Optimize Credit Card Payoff",
    summary: "Paying an extra $500/month on Chase Sapphire Reserve eliminates the balance in 9 months, saving $480 in interest.",
    impact: 480,
    impactLabel: "Interest Saved",
    action: "Set Up Auto-Pay",
  },
  {
    id: "ai-3",
    type: "insurance",
    priority: "medium",
    title: "Underinsured Business Assets",
    summary: "Your Business Owners Policy covers $1.5M but combined business assets exceed $2.1M. Consider increasing coverage.",
    impact: 600000,
    impactLabel: "Uncovered Assets",
    action: "Review Coverage",
  },
  {
    id: "ai-4",
    type: "investment",
    priority: "low",
    title: "Cash Drag on Savings",
    summary: "Your Chase checking holds $84K — moving $60K to your Marcus HY Savings at 4.75% APY earns $2,850/year.",
    impact: 2850,
    impactLabel: "Annual Earnings",
    action: "Transfer Funds",
  },
  {
    id: "ai-5",
    type: "tax",
    priority: "high",
    title: "Q1 Estimated Tax Due Feb 15",
    summary: "Based on your combined business income, your Q1 estimated tax payment of ~$18,400 is due February 15th.",
    impact: 18400,
    impactLabel: "Payment Due",
    action: "Review Tax Estimate",
  },
];

export const netWorthHistory = [
  { month: "Jul", value: 2480000 },
  { month: "Aug", value: 2520000 },
  { month: "Sep", value: 2590000 },
  { month: "Oct", value: 2640000 },
  { month: "Nov", value: 2710000 },
  { month: "Dec", value: 2780000 },
  { month: "Jan", value: 2847500 },
];
